### ISSUE TITLE
Edit to duct tape makes you unable to reload misc repair kit

### ISSUE THREAD

**Issue by PGR-14** [FrontierMods/Gunsmith#3]
Probably w/ all other reloadable things using duct tape too

**Comment by Hyperseeker** [comment]
Frankly, I'm shocked that this mod still receives any attention: it's been dead and buried for over 3 years now, with the most recent update simply saying "Other mods are being worked on".

Initially I was skeptical that this mod, of all things, would be causing any issues with duct tape, given that all it does is add gunmod functionality to it. Because it's a `copy-from` definition in Gunsmith, every other property comes from the base game. If there would be any issues with the item, it would be because of the base game, not the mod.

But, my ADHD loves distractions, so I went ahead and tested anyway.

The short answer is: no, it's not Gunsmith. The latest experimental I could get from *DDA*'s Github ([this one](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-03-24-0121), `cdda-experimental-2024-03-24-0121`) has the exact same issue with duct tape rolls and misc. repair kits as it had for, well, [a very long time now](https://github.com/CleverRaven/Cataclysm-DDA/pull/65531). This was true with or without Gunsmith on the same build of the game. You could reload the repair kit with loose duct tape, but not with the tape hidden "inside" a cardboard roll, in both cases.

For what it's worth, there is a [possible fix](https://github.com/CleverRaven/Cataclysm-DDA/pull/72554) coming to the base game at some point. However, given that your game version seems to be lagging behind by almost 11 months – the time when the cardboard roll change for duct tape was introduce – you might not see this fix for a very long time still.

That said, thank you for reminding me about the state of this repo. It really ought to be archived. A mod that has last been tested on a release three-and-a-half years ago is not much of a mod anymore.
